### ISSUE TITLE
Can't define or retreive the session id

### ISSUE THREAD

**Issue by nicolaslevy** [montevideo-tech/videojs-cmcd#25]
The following cases need to be covered:

- The session ID sent in the CMCD data should be configurable by the plugin user through an API provided by the plugin.
- I f the user does not set a session ID, the plugin should generate a random UUID4. The plugin user should be able to retrieve the auto-generated UUID using an API provided by the plugin.

Acceptance criteria:
- The plugin must have a setter and a getter for the session ID.
- The API for setting and retrieving the session ID should be documented in the README.
- The basic usage example in the README should be updated to demonstrate how to set and retrieve the session ID.

**Comment by CamiloBorba09** [comment]
To solve this bug, it is necessary to check the documentation provided by VideoJS for advanced plugins. https://videojs.com/guides/plugins/

This project was created with the VideoJS plugin generator, but for some reason, the generated plugin differs from the documentation.

It will be necessary to identify what the differences are and if it is necessary to make any changes to the plugin in order to then be able to solve this bug.

This ticket is goint to be moved to the Backlog
